#!/usr/bin/env python
import sys, time

PASSWORD = "CHAOS"

if len(sys.argv[1]) > len(PASSWORD):
    exit(2)

for i in range(len(sys.argv[1])):
    if PASSWORD[i] == sys.argv[1][i]:
        time.sleep(0.1)

if PASSWORD != sys.argv[1]:
    exit(1)
